import Head from 'next/head';
import { useSelector } from 'react-redux';
import type { RootState } from '@/redux/store';
import Card from '@/components/Card';

export default function Home() {
  const articles = useSelector((state: RootState) => state.articles);

  return (
    <div>
      <Head>
        <title>Blog App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <div
        style={{ margin: '30px 0', display: 'flex', justifyContent: 'center' }}
      >
        <h1>Articles</h1>
      </div>

      <div className="container flex">
        {articles.map(article => {
          return <Card key={article.id} article={article} />;
        })}
      </div>
    </div>
  );
}
