import Head from 'next/head';
import type { RootState } from '@/redux/store';
import Card from '@/components/Card';
import Hero from '@/components/Hero';
import { useAppSelector } from '@/hooks/hooks';

export default function Home() {
  const articles = useAppSelector(
    (state: RootState) => state.articles.filterArticles
  );

  return (
    <>
      <Head>
        <title>Blog App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      {/* Hero Section */}
      <section>
        <Hero />
      </section>

      {/* Article Section */}
      <div
        style={{ margin: '30px 0', display: 'flex', justifyContent: 'center' }}
      >
        <h1>Articles</h1>
      </div>

      <section className="container flex">
        {articles.map(article => {
          return <Card key={article.id} article={article} />;
        })}
      </section>
    </>
  );
}
